# Commented lines that are ignored starte with the '#' mark.
# A helpful tutorial for more information on make
# https://www.cs.swarthmore.edu/~newhall/unixhelp/howto_makefiles.html

all : music.c radio.c
	gcc -std=c11 -o radio music.c radio.c
clean :
	rm radio
