# Commented lines that are ignored starte with the '#' mark.
# A helpful tutorial for more information on make
# https://www.cs.swarthmore.edu/~newhall/unixhelp/howto_makefiles.html

all : painters.c 
	gcc -std=c11 -g -o painters painters.c -lpthread
clean :
	rm painters
